import Footer from "./_components/Footer";
import "./globals.css";
import { Epilogue } from 'next/font/google'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
 
const epilogue = Epilogue({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Disha Learning",
  description: "Generated by create next app",
};

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={epilogue.className}>
        {children}
        <Footer />
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2591722971865211"
     crossorigin="anonymous"></script>
        </body>
    </html>
  );
}
