import { Inter } from "next/font/google";
import "./globals.css";

import { Epilogue } from 'next/font/google'
import Footer from "@/components/footer";
const epilogue = Epilogue({ subsets: ['latin'] })

export const metadata = {
  title: "Disha Learning",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <script rel="preconnect" src="https://kit.fontawesome.com/c57dc26725.js" crossorigin="anonymous"></script>
      </head>
      <body className={`${epilogue.className}`}>
        <main>
        {children}
        </main>
        <Footer />
        </body>
    </html>
  );
}
