import Footer from "./_components/Footer";
import Navbar from "./_components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Disha Learning",
  description: "Generated by create next app",
};

import { Epilogue } from 'next/font/google'
 
const epilogue = Epilogue({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={epilogue.className}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
